user=dnsmasq
group=dnsmasq
interface=*
address=/#/10.10.10.3
# TODO: Can we log all requests?
# TODO: Return real address for allowed destinations. Or we *could* use INetSim by statically configuring the real IP addresses.