FROM debian:stable-slim

RUN apt-get update && apt-get install -y inetsim && rm -rf /var/lib/apt/lists/*
# We need to use our own root CA cert instead of INetSim's default cert, otherwise clients in the sandbox (at least curl)
# complain about a weak signature digest algorithm ("SSL certificate problem: CA signature digest algorithm too weak")
COPY sslsplit-ca.key sslsplit-ca.crt /var/lib/inetsim/certs/
RUN chown -R inetsim:inetsim  /var/lib/inetsim/certs

ENTRYPOINT ["inetsim"]